export const INITIALIZELD = 'INITIALIZELD';
export const TOGGLE_FEATURE = 'TOGGLE_FEATURE';

/* AUTHENTICATION */
export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';

/* SERVICE */
export const SERVICE_REQUEST = 'SERVICE_REQUEST';

/* WORKFLOW DETAILS */
export const DETAILS_SET = 'DETAILS_SET';
export const DETAILS_GET = 'DETAILS_GET';

/* APP STATE ACTIONS */
export const SET_RECALC = 'SET_RECALC';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';
export const APPSTATE_SET = 'APPSTATE_SET';
export const APPSTATE_ERROR = 'APPSTATE_ERROR';

export const APP_ERROR = 'APP_ERROR';
export const APP_ERROR_CLEAR = 'APP_ERROR_CLEAR';
export const APP_MODAL_ERROR = 'APP_MODAL_ERROR';

export const COMPLETED_TASKS_SET = 'COMPLETED_TASKS_SET';

export const AUTH = 'AUTH';

export const POLICY_SEARCH = 'POLICY_SEARCH';
export const QUOTE_SEARCH = 'QUOTE_SEARCH';

export const GET_POLICY = 'GET_POLICY';


export const SEARCH = 'SEARCH';
export const RESET_SEARCH = 'RESET_SEARCH';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';

export const SET_QUOTE = 'SET_QUOTE';

export const SET_AGENCIES = 'SET_AGENCIES';
export const SET_AGENTS = 'SET_AGENTS';
export const SET_AGENCY = 'SET_AGENCY';
