version: "2"
services:
  harmony-web:
    build:
      context: .
      dockerfile: dev.dockerfile
    container_name: harmony-web
    environment:
      - PORT=80
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=runBoth
      - REACT_APP_API_URL=http://www.harmony-ins.com/api
    ports:
     - "3000:80"
  heimdall:
    image: exzeo/heimdall:develop
    container_name: heimdall
    environment:
      - PORT=80
      - MONGO_URL=mongodb://mongo-heimdall/heimdall
    depends_on:
      - mongo-heimdall
  harmony-api:
    image: exzeo/harmony-api:develop
    container_name: harmony-api
    environment:
      - PORT=80
      - CG_URL=http://cc_cgapi:9000
      - LD_SDK=sdk-509372b6-816c-4a27-9c31-af85f50bb27c
      - CASACLUE_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Rjb25zdW1lckBleHplby5jb20iLCJrZXkiOiJBT3hxWXoyNmRycVp6aW5SQW1UbDNvSTNSOXliMTc5R3NJN1A5RHl2cjcrVjhKRUxIdWdkYWxaK1NjYm9NUEtmRUE9PSIsImlzcyI6IkNvbnN1bWVyYXBpIiwiYXVkIjoiaHR0cHM6Ly9jb25zdW1lcnFhLmNhc2FjbHVlLmNvbSIsImV4cCI6MTQ5ODQwNTcyMSwibmJmIjoxNDgyODUzNzIxfQ.kc-FudLXIA6FE8OCJcyqRM_sG6Nbz9juksOaHNCgmsw
    command: npm start
  mongo-heimdall:
    image: mongo
    container_name: mongo-heimdall
  bifrost:
    image: exzeo/bifrost:develop
    command: /usr/local/openresty/nginx/sbin/nginx
    container_name: bifrost
    environment:
      - ALLOW_CORS=true
    ports:
      - "4000:3000"
    depends_on:
      - harmony-web
      - harmony-api
