version: "2"
services:
  harmony-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - "NPM_TOKEN=${NPM_TOKEN}"
    command: npm run start
    container_name: harmony-web
    environment:
      - PORT=80
      - EXTEND_ESLINT=true
      - REACT_APP_VERSION="1.0"
      - REACT_APP_API_URL=https://api.harmony-ins.com
      - REACT_APP_AQA_SSO_URL=https://www-qa.typtap.com/agency/agents/sso
      - REACT_APP_DOCUMENT_URL=https://docs.harmony-ins.com
      - REACT_APP_COMPANY_ASSETS_URL=https://assets-qa.typtap.com
      # auth0
      - REACT_APP_AUTH0_PRIMARY_URL=http://devcsr.harmony-ins.com:8383
      - REACT_APP_AUTH0_DOMAIN=ashton-sandbox.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=_aVZ55R37kcyZ3NtQcps0bwZ09YYdPLd
      - REACT_APP_AUTH0_CONNECTION=ashton-sandbox
      - REACT_APP_AUTH0_AUDIENCE=http://harmony-sandbox
    ports:
      - "8383:80"
