version: "2"
services:
  harmony-web:
    build:
      context: .
      dockerfile: Dockerfile.cypress
      args:
      - NPM_TOKEN=TOKEN_GOES_HERE
    container_name: harmony-web-cypress
    environment:
      # test cypress against sandbox environment
      - CYPRESS_BASE_URL=https://agency.harmony-ins.com

      # # point to local
      # - CYPRESS_BASE_URL=ttp://devagent.harmony-ins.com:8383

      # # point to local using mock-auth0
      # - CYPRESS_USE_MOCK_AUTH0=true


