FROM node:10-alpine

LABEL maintainer=Exzeo

RUN apk update && apk --no-cache add bash libc6-compat g++ make python

ARG NPM_TOKEN

WORKDIR /app/
COPY cypress/package.json /app/package.json
RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
RUN npm install

ADD cypress/ cypress.json app/

# Install app
RUN npm cache clean --force && \ 
rm -f .npmrc

CMD ["npm", "run", "cypress", "--", "--headless"]
