FROM cypress/base:10

LABEL maintainer=Exzeo

ARG NPM_TOKEN

WORKDIR /app

COPY cypress/package.json /app/package.json
RUN echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc && ls -la
RUN npm install

ADD cypress.json cypress/ ./

# Install app
RUN npm cache clean --force && rm -f .npmrc && ls -la

CMD ["npm", "run", "cypress", "--", "--headless"]
