export const INITIALIZELD = 'INITIALIZELD';
export const TOGGLE_FEATURE = 'TOGGLE_FEATURE';

/* AUTHENTICATION */
export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';
export const AUTH_ME = 'AUTH_ME';

/* SEARCH CONFIG */
export const CLEAR_SEARCH_CONFIG = 'CLEAR_SEARCH_CONFIG';
export const SET_SEARCH_CONFIG = 'SET_SEARCH_CONFIG';


/* Details */
export const SET_DETAILS = 'SET_DETAILS';
export const GET_DETAILS = 'GET_DETAILS';
