export const INITIALIZELD = 'INITIALIZELD';
export const TOGGLE_FEATURE = 'TOGGLE_FEATURE';

/* AUTHENTICATION */
export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATE_ERROR = 'AUTHENTICATE_ERROR';

/* CG */
export const CG_START = 'CG_START';
export const CG_ACTIVE_TASK = 'CG_ACTIVE_TASK';
export const CG_COMPLETE = 'CG_COMPLETE';
export const CG_ERROR = 'CG_ERROR';

/* SERVICE */
export const SERVICE_REQUEST = 'SERVICE_REQUEST';

/* WORKFLOW DETAILS */
export const DETAILS_SET = 'DETAILS_SET';
export const DETAILS_GET = 'DETAILS_GET';

/* APP STATE ACTIONS */
export const APPSTATE_SET = 'APPSTATE_SET';
export const APPSTATE_ERROR = 'APPSTATE_ERROR';

export const APP_ERROR = 'APP_ERROR';
export const APP_ERROR_CLEAR = 'APP_ERROR_CLEAR';

export const COMPLETED_TASKS_SET = 'COMPLETED_TASKS_SET';

export const AUTH = 'AUTH';

export const POLICY_SEARCH = 'POLICY_SEARCH';
export const QUOTE_SEARCH = 'QUOTE_SEARCH';

