import { stub } from '../helpers';

export default (useConfig = false) => cy.server()
.route('POST', '/svc?fetchAgency', useConfig ? stub('fx:stubs/fetchAgency') : 'fx:stubs/fetchAgency')
.route('POST', '/svc?fetchAddresses', useConfig ? stub('fx:stubs/fetchAddresses') : 'fx:stubs/fetchAddresses').as('fetchAddresses')
.route('POST', '/cg/start?quoteModel', useConfig ? stub('fx:stubs/quoteModel') : 'fx:stubs/quoteModel')
.route('POST', '/svc?getQuoteServiceRequest', useConfig ? stub('fx:stubs/getQuoteServiceRequest') : 'fx:stubs/getQuoteServiceRequest').as('getQuoteServiceRequest')
.route('POST', '/cg/complete?search', useConfig ? stub('fx:stubs/search') : 'fx:stubs/search')
.route('POST', '/cg/complete?chooseAddress', useConfig ? stub('fx:stubs/chooseAddress') : 'fx:stubs/chooseAddress')
.route('POST', '/svc?fetchAgentsByAgencyCode', useConfig ? stub('fx:stubs/fetchAgentsByAgencyCode') : 'fx:stubs/fetchAgentsByAgencyCode')
.route('POST', '/svc?getZipcodeSettings', useConfig ? stub('fx:stubs/getZipcodeSettings') : 'fx:stubs/getZipcodeSettings')
.route('POST', '/cg/complete?askAdditionalCustomerData', useConfig ? stub('fx:stubs/askAdditionalCustomerData') : 'fx:stubs/askAdditionalCustomerData')
// .route('POST', '/cg/moveToTask?askAdditionalCustomerData', useConfig ? stub('fx:stubs/moveToTask/askAdditionalCustomerData') : 'fx:stubs/moveToTask/askAdditionalCustomerData')
.route('POST', '/cg/complete?askUWAnswers', useConfig ? stub('fx:stubs/askUWAnswers') : 'fx:stubs/askUWAnswers')
// .route('POST', '/cg/moveToTask?askUWAnswers', useConfig ? stub('fx:stubs/moveToTask/askUWAnswers') : 'fx:stubs/moveToTask/askUWAnswers')
.route('POST', '/cg/complete?askToCustomizeDefaultQuote', useConfig ? stub('fx:stubs/askToCustomizeDefaultQuote') : 'fx:stubs/askToCustomizeDefaultQuote')
// .route('POST', '/cg/moveToTask?askToCustomizeDefaultQuote', useConfig ? stub('fx:stubs/askToCustomizeDefaultQuote') : 'fx:stubs/askToCustomizeDefaultQuote')
.route('POST', '/cg/complete?showCustomizedQuoteAndContinue', useConfig ? stub('fx:stubs/showCustomizedQuoteAndContinue') : 'fx:stubs/showCustomizedQuoteAndContinue')
.route('POST', '/cg/complete?sendEmailOrContinue', useConfig ? stub('fx:stubs/sendEmailOrContinue') : 'fx:stubs/sendEmailOrContinue')
// .route('POST', '/cg/moveToTask?sendEmailOrContinue', useConfig ? stub('fx:stubs/moveToTask/sendEmailOrContinue') : 'fx:stubs/moveToTask/sendEmailOrContinue')
.route('POST', '/cg/complete?showAssumptions', useConfig ? stub('fx:stubs/showAssumptions') : 'fx:stubs/showAssumptions')
.route('POST', '/cg/complete?addAdditionalAIs', useConfig ? stub('fx:stubs/addAdditionalAIs/base') : 'fx:stubs/addAdditionalAIs/base')
.route('POST', '/cg/moveToTask?addAdditionalAIs', useConfig ? stub('fx:stubs/moveToTask/addAdditionalAIs') : 'fx:stubs/moveToTask/addAdditionalAIs')
.route('POST', '/cg/complete?askAdditionalQuestions', useConfig ? stub('fx:stubs/askAdditionalQuestions') : 'fx:stubs/askAdditionalQuestions')
// .route('POST', '/cg/moveToTask?askAdditionalQuestions', useConfig ? stub('fx:stubs/moveToTask/askAdditionalQuestions') : 'fx:stubs/moveToTask/askAdditionalQuestions')
.route('POST', '/cg/complete?editVerify', useConfig ? stub('fx:stubs/editVerify') : 'fx:stubs/editVerify')
// .route('POST', '/cg/moveToTask?editVerify', useConfig ? stub('fx:stubs/moveToTask/editVerify') : 'fx:stubs/moveToTask/editVerify')
.route('POST', '/cg/complete?askScheduleInspectionDates', useConfig ? stub('fx:stubs/askScheduleInspectionDates') : 'fx:stubs/askScheduleInspectionDates')
