export const setRouteAliases = () =>
  cy
    .server()
    .route({ method: 'POST', url: '/svc?fetchAddresses' })
    .as('fetchAddresses')
    .route({ method: 'POST', url: '/svc?fetchQuotes' })
    .as('fetchQuotes')
    .route({ method: 'POST', url: '/svc?searchPolicy' })
    .as('searchPolicy')
    .route({ method: 'POST', url: '/svc?getZipcodeSettings' })
    .as('getZipcodeSettings')
    .route({ method: 'POST', url: '/svc?sendQuoteSummary' })
    .as('sendQuoteSummary')
    .route({ method: 'POST', url: '/svc?quoteManager.updateQuote' })
    .as('updateQuote')
    .route({ method: 'POST', url: '/svc?quoteManager.retrieveQuote' })
    .as('retrieveQuote')
    .route({ method: 'POST', url: '/svc?quoteManager.verifyQuote' })
    .as('verifyQuote')
    .route({ method: 'POST', url: '/svc?quoteManager.sendApplication' })
    .as('sendApplication')
    .route({ method: 'POST', url: '/svc?getBillingOptions' })
    .as('getBillingOptions')
    .route({ method: 'POST', url: '/svc?UWQuestions' })
    .as('UWQuestions')
    .route({ method: 'POST', url: '/svc?getQuote' })
    .as('getQuote')
    .route({ method: 'POST', url: '/svc?getLatestPolicy' })
    .as('getLatestPolicy')
    .route({ method: 'POST', url: '/questions' })
    .as('getQuestions')
    .route({ method: 'POST', url: '/svc?fetchAgentsByAgencyCode' })
    .as('getAgents')
    .route({ method: 'POST', url: '/svc?searchPolicy' })
    .as('searchPolicy')
    .route({ method: 'POST', url: '/svc?quoteManager.searchQuotes' })
    .as('fetchQuotes')
    .route({ method: 'POST', url: '/svc?quoteManager.createQuote' })
    .as('createQuote')
    .route({ method: 'POST', url: '/svc?listReport' })
    .as('listReport')
    .route({ method: 'POST', url: '/svc?getReportById' })
    .as('getReportById');
