version: "2"
networks:
    web:
      driver: bridge
services:
  harmony-web:
    build:
      context: .
      dockerfile: ../.docker/dev.dockerfile
    command: ls
    expose:
     - "3001"
    ports:
     - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
  heimdall:
    image: exzeo/heimdall:develop
    environment:
      - PORT=80
      - MONGO_URL=mongodb://mongo/heimdall
    networks:
      - web
    depends_on:
      - mongo
  harmony-api:
    image: exzeo/harmony-api:develop
    environment:
      - PORT=80
      - LD_SDK=sdk-509372b6-816c-4a27-9c31-af85f50bb27c
      - CASACLUE_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3Rjb25zdW1lckBleHplby5jb20iLCJrZXkiOiJBT3hxWXoyNmRycVp6aW5SQW1UbDNvSTNSOXliMTc5R3NJN1A5RHl2cjcrVjhKRUxIdWdkYWxaK1NjYm9NUEtmRUE9PSIsImlzcyI6IkNvbnN1bWVyYXBpIiwiYXVkIjoiaHR0cHM6Ly9jb25zdW1lcnFhLmNhc2FjbHVlLmNvbSIsImV4cCI6MTQ5ODQwNTcyMSwibmJmIjoxNDgyODUzNzIxfQ.kc-FudLXIA6FE8OCJcyqRM_sG6Nbz9juksOaHNCgmsw
    networks:
      - web
    command: npm start
  mongo:
    image: mongo
    networks:
      - web
  bifrost:
    image: exzeo/bifrost:develop
    command: /usr/local/openresty/nginx/sbin/nginx
    environment:
      - ALLOW_CORS=true
    networks:
      - web
    ports:
      - "4000:3000"
    depends_on:
      - harmony-web
      - harmony-api
